name: Checks
on:
  push:
    branches:
      - main
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none

      - name: Setup PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          export SNIFFS_DIR=/tmp/sniffs
          git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR
          git clone -b master --depth 1 https://github.com/PHPCompatibility/PHPCompatibility.git $SNIFFS_DIR/PHPCompatibility
          git clone -b master --depth 1 https://github.com/PHPCompatibility/PHPCompatibilityWP.git $SNIFFS_DIR/PHPCompatibilityWP
          git clone -b master --depth 1 https://github.com/PHPCompatibility/PHPCompatibilityParagonie.git $SNIFFS_DIR/PHPCompatibilityParagonie
          php phpcs.phar --config-set installed_paths $SNIFFS_DIR,$SNIFFS_DIR/PHPCompatibility,$SNIFFS_DIR/PHPCompatibilityWP,$SNIFFS_DIR/PHPCompatibilityParagonie

      - name: Log debug information
        run: |
          php --version
          php phpcs.phar --version
          php phpcs.phar -i

      - name: PHP Syntax
        run: find . \( -name '*.php' \) -exec php -lf {} \;

      - name: PHP Compatibility 7.0+
        run: |
          php phpcs.phar -p -s -v -n . --standard=phpcompat.xml.dist

      - name: Coding Standards
        run: |
          php phpcs.phar -p -s -v -n . --standard=phpcs.xml.dist
